import "./globals.css";
import classNames from "classnames";
import { Montserrat } from "next/font/google";
import Sidebar from "./components/layout/aside/sidebar";
import Providers from "@/providers";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { Logo } from "./components/layout/aside/sidebar/logo";

import { getDictionary } from "../../../getDictionary";
const Mont = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "PsyMI",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const lang = await getDictionary(params.lang);
  return (
    <html lang={lang}>
      <body
        className={
          Mont.className +
          " " +
          "min-h-screen pt-[30px] pb-[50px] px-[20px] md:px-[40px] lg:px-[70px] bg-[#F2F5F8] relative"
        }
      >
        <ToastContainer
          closeButton={false}
          className={"font-montserrat text-[14px] text-center h-[20px]"}
        />
        <main>
          <Providers>
            <div className='xl:mb-[12px] xl:fixed'>
              <Logo lang={lang} />
            </div>
            <div className='fixed z-50 left-0 right-0 bottom-0 xl:left-[70px] xl:right-auto xl:bottom-auto xl:top-[90px]'>
              <Sidebar lang={lang} />
            </div>
            <div className='xl:ml-[270px] 2xl:ml-[350px]'>{children}</div>
          </Providers>
        </main>
      </body>
    </html>
  );
}
